[package]
name = "php-rs-valgrind"
version = "0.1.0"
edition = "2021"

[dependencies]
ext-php-rs = "*"

[lib]
crate-type = ["cdylib"]

[patch.crates-io]
ext-php-rs = { path = "/home/ptondereau/Code/rust/ext-php-rs" }